version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1


jobs:
  build:
    docker:
      - image: cimg/node:16.16.0


    steps:
      - checkout
      - run: npm install
      - run: npm run build


  test:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test



workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - build
            - test
          filters:
            branches:
              only: main